<?php
/**
 * ExtendedProducerResponsibilityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * OpenAPI spec version: 1.18.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * ExtendedProducerResponsibilityTest Class Doc Comment
 *
 * @category    Class
 * @description This type provides IDs for the producer or importer related to the new item, packaging, added documentation, or an eco-participation fee. In some markets, such as in France, this may be the importer of the item.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExtendedProducerResponsibilityTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ExtendedProducerResponsibility"
     */
    public function testExtendedProducerResponsibility()
    {
    }

    /**
     * Test attribute "eco_participation_fee"
     */
    public function testPropertyEcoParticipationFee()
    {
    }

    /**
     * Test attribute "producer_product_id"
     */
    public function testPropertyProducerProductId()
    {
    }

    /**
     * Test attribute "product_documentation_id"
     */
    public function testPropertyProductDocumentationId()
    {
    }

    /**
     * Test attribute "product_package_id"
     */
    public function testPropertyProductPackageId()
    {
    }

    /**
     * Test attribute "shipment_package_id"
     */
    public function testPropertyShipmentPackageId()
    {
    }
}
