<?php
/**
 * ProductSafetyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * OpenAPI spec version: 1.18.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * ProductSafetyTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used to define the &lt;b&gt;pictograms&lt;/b&gt; and &lt;b&gt;statement&lt;/b&gt; containers, and the optional &lt;b&gt;component&lt;/b&gt; field, that provide product safety and compliance related information.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductSafetyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProductSafety"
     */
    public function testProductSafety()
    {
    }

    /**
     * Test attribute "component"
     */
    public function testPropertyComponent()
    {
    }

    /**
     * Test attribute "pictograms"
     */
    public function testPropertyPictograms()
    {
    }

    /**
     * Test attribute "statements"
     */
    public function testPropertyStatements()
    {
    }
}
