<?php
/**
 * LocationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * OpenAPI spec version: 1.18.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LocationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LocationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createInventoryLocation
     *
     * .
     *
     */
    public function testCreateInventoryLocation()
    {
    }

    /**
     * Test case for deleteInventoryLocation
     *
     * .
     *
     */
    public function testDeleteInventoryLocation()
    {
    }

    /**
     * Test case for disableInventoryLocation
     *
     * .
     *
     */
    public function testDisableInventoryLocation()
    {
    }

    /**
     * Test case for enableInventoryLocation
     *
     * .
     *
     */
    public function testEnableInventoryLocation()
    {
    }

    /**
     * Test case for getInventoryLocation
     *
     * .
     *
     */
    public function testGetInventoryLocation()
    {
    }

    /**
     * Test case for getInventoryLocations
     *
     * .
     *
     */
    public function testGetInventoryLocations()
    {
    }

    /**
     * Test case for updateInventoryLocation
     *
     * .
     *
     */
    public function testUpdateInventoryLocation()
    {
    }
}
